# Generator params
GENERATOR = 'generator'
GENERATOR_PARAMS = 'generator_params'
GENERATOR_TYPE = 'generator_type'
TARGETS = 'targets'
CONFIG_SPACE = 'config_space'
N_TRIALS = 'n_trials'
PLOT_REFERENCE_FEATURE = 'plot_reference_feature'
SYSTEM_PARAMS = 'system_params'