name: gedi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.26.4
  - pandas
  - matplotlib
  - pip
  - pip:
      - altair==5.3.0
      - attrs==23.2.0
      - blinker==1.8.2
      - cachetools==5.4.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - configspace==0.7.1
      - cvxopt==1.3.2
      - dask==2024.4.1
      - dask-jobqueue==0.8.5
      - deprecation==2.1.0
      - distributed==2024.4.1
      - emcee==3.1.4
      - feeed==1.2.0
      - fsspec==2024.3.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - idna==3.7
      - imbalanced-learn==0.12.2
      - imblearn==0.0
      - intervaltree==3.1.0
      - jinja2==3.1.3
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - levenshtein==0.23.0
      - llvmlite==0.42.0
      - locket==1.0.0
      - lxml==5.2.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - more-itertools==10.2.0
      - msgpack==1.0.8
      - networkx==3.2.1
      - numba==0.59.1
      - numpy==1.26.4
      - opyenxes==0.3.0
      - partd==1.4.1
      - pm4py==2.7.2
      - protobuf==5.27.2
      - pyarrow==17.0.0
      - pydeck==0.9.1
      - pydotplus==2.0.2
      - pynisher==1.0.10
      - pyrfr==0.9.0
      - pywin32==306
      - pyyaml==6.0.1
      - rapidfuzz==3.8.1
      - referencing==0.35.1
      - regex==2023.12.25
      - requests==2.32.3
      - rich==13.7.1
      - rpds-py==0.19.0
      - scikit-learn==1.4.0
      - seaborn==0.13.2
      - shap==0.45.1
      - slicer==0.0.8
      - smac==2.0.2
      - smmap==5.0.1
      - sortedcontainers==2.4.0
      - streamlit==1.36.0
      - stringdist==1.0.9
      - tabulate==0.9.0
      - tblib==3.0.0
      - tenacity==8.5.0
      - toolz==0.12.1
      - tqdm==4.65.0
      - urllib3==2.2.1
      - watchdog==4.0.1
      - xgboost==2.1.0
      - zict==3.0.0
