name: Merge and Push to Other Repository

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch of the current repository

jobs:
  import_pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the current repository (your repository's main branch)
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Get Repository Name
        id: get_repo_name
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}

      # Step 2: Set up the target repository
      - name: Remove existing directory
        run: |
          rm -rf gedi  # Ensure the directory is clean before cloning
      - name: Set up target repository
        run: |
          git clone https://$GITHUB_ACTOR:${{ secrets.TARGET_REPO_PAT }}@github.com/lmu-dbs/gedi.git
          cd gedi
          git checkout main  # Ensure we are on the main branch


      # Step 3: Merge external repo's main into the new branch
      - name: Merge external repo's main into the new branch
        run: |
          cd gedi
          git remote add source ../  # Assuming the current repo is in the parent directory
          git fetch source
          # Checkout the branch from the current repo
          CURRENT_BRANCH=$(echo $GITHUB_REF | awk -F'/' '{print $3}')  # Get the current branch name
          git checkout -b temp-branch source/$CURRENT_BRANCH  # Create a temporary branch from current repo's branch
          git merge origin/main --allow-unrelated-histories

      # Step 4: Push the changes to the current repository
      - name: Push merged changes to current repository
        run: |
          cd target-repository
          git push origin temp-branch  # Push the temporary branch to the target repo


      # Step 6: Open PR from temp-branch in current repo to the current branch
      - name: Create PR from temp-branch to current branch
        run: |
          CURRENT_BRANCH=$(echo $GITHUB_REF | awk -F'/' '{print $3}')  # Get the current branch name
          curl -X POST -H "Authorization: token ${{ secrets.EXTERNAL_REPO_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$GITHUB_REPOSITORY/pulls \
          -d "{\"title\":\"Merge main from external repo into $CURRENT_BRANCH\",\"head\":\"temp-branch\",\"base\":\"$CURRENT_BRANCH\",\"body\":\"Automated PR from GitHub Actions\"}"


  export_pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the current repository (your repository's main branch)
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Get Repository Name
        id: get_repo_name
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}

      # Step 2: Set up the target repository
      - name: Remove existing directory
        run: |
          rm -rf gedi  # Ensure the directory is clean before cloning
      - name: Set up target repository
        run: |
          git clone https://$GITHUB_ACTOR:${{ secrets.TARGET_REPO_PAT }}@github.com/lmu-dbs/gedi.git
          cd gedi
          git checkout main  # Ensure we are on the main branch

      # Step 3: Push the current branch to the target repository
      - name: Push current branch to target repository
        run: |
          cd gedi
          git checkout -b temp-branch  # Create a new branch from main
          git merge origin/main
          git push origin temp-branch  # Push the current branch to target repo

      # Step 4: Create a PR from the current branch to the target repo's main
      - name: Create PR from current branch to target repo's main
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.TARGET_REPO_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/lmu-dbs/gedi/pulls \
          -d "{\"title\":\"Merge temp-branch into main\",\"head\":\"$GITHUB_REPOSITORY:temp-branch\",\"base\":\"main\",\"body\":\"Automated PR from GitHub Actions\"}"
