name: GEDI Test

# Specifies when the action should run
on:
  pull_request:
    branches:
      - main
      - bpm24
      - demo-icpm24
  workflow_dispatch:

# Specifies the jobs that are to be run
jobs:
  test_feature-extraction:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install feeed
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python main.py -a config_files/pipeline_steps/feature_extraction.json

    - name: Compare output
      run: diff data/validation/test_feat.csv data/test_feat.csv

  test_generation:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get install build-essential python3 python3-dev

    - name: Install feeed
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python main.py -a config_files/pipeline_steps/generation.json

    - name: Compare output 1
      run: 
        diff data/validation/genEL1_04_02.json output/features/2_enself_rt20v/genEL1_04_02.json

    - name: Compare output 2
      run: 
        diff data/validation/genEL2_07_04.json output/features/2_enself_rt20v/genEL2_07_04.json

    - name: Compare output 3
      run:
        diff data/validation/genEL3_04_nan.json output/features/2_enself_rt20v/genEL3_04_nan.json

    - name: Compare output 4
      run: 
        diff data/validation/genEL4_nan_02.json output/features/2_enself_rt20v/genEL4_nan_02.json

  test_benchmark:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install feeed
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python main.py -a config_files/pipeline_steps/benchmark.json

    - name: Convert output and validation to same encoding
      run: |
        iconv -f UTF-8 -t ASCII data/validation/test_benchmark.csv > data/validation/test_benchmark.csv
        iconv -f UTF-8 -t ASCII output/benchmark/test_benchmark.csv > output/benchmark/test_benchmark.csv

    - name: Compare output
      run: diff data/validation/test_benchmark.csv output/benchmark/test_benchmark.csv

  test_augmentation:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install feeed
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python main.py -a config_files/pipeline_steps/augmentation.json

  test_evaluation-plotter:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get install build-essential python3 python3-dev

    - name: Install feeed
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python main.py -a config_files/pipeline_steps/evaluation_plotter.json

  test_integration:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get install build-essential python3 python3-dev

    - name: Install feeed
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python main.py -a config_files/test/experiment_test.json

  test_grid_experiments_script:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get install build-essential python3 python3-dev

    - name: Install feeed
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python gedi/utils/execute_grid_experiments.py config_files/test

    - name: Convert output and validation to same encoding
      run: iconv -f UTF-8 -t ASCII output/features/generated/2_bpic_features/2_ense_enseef_feat.csv > data/validation/2_ense_enseef_feat.csv

    - name: Compare output
      run: diff data/validation/2_ense_enseef_feat.csv output/features/generated/2_bpic_features/2_ense_enseef_feat.csv

  test_abbrv:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get install build-essential python3 python3-dev

    - name: Install feeed
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python main.py -a config_files/test/test_abbrv_generation.json

    - name: Compare output
      run:
        diff data/validation/2_ense_rmcv_feat.csv output/test/igedi_table_1/2_ense_rmcv_feat.csv

  test_pypible_generate_event_logs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get install build-essential python3 python3-dev

    - name: Install feeed
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python -c "from gedi import GenerateEventLogs;default_params = {'generator_params': {'experiment': {'ratio_top_20_variants': 0.2, 'epa_normalized_sequence_entropy_linear_forgetting': 0.4}, 'config_space': {'mode': [5, 20], 'sequence': [0.01, 1], 'choice': [0.01, 1], 'parallel': [0.01, 1], 'loop': [0.01, 1], 'silent': [0.01, 1], 'lt_dependency': [0.01, 1], 'num_traces': [10, 101], 'duplicate': [0], 'or': [0]}, 'n_trials': 50}}; GenerateEventLogs(default_params)"