name: GEDI Test

# Specifies when the action should run
on:
  pull_request:
    branches:
      - main
      - bpm24

# Specifies the jobs that are to be run
jobs:
  test_feature-extraction:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install feeed
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python main.py -o config_files/options/baseline.json -a config_files/algorithm/feature_extraction.json

    - name: Compare output
      run: diff data/test_feat.csv data/test_feat.csv

  test_generation:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get install build-essential python3 python3-dev

    - name: Install feeed
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python main.py -o config_files/options/baseline.json -a config_files/algorithm/generation.json

    - name: Compare output
      run: diff output/features/grid_feat/2_enself_rt20v/genELexperiment2_07_04.json output/features/grid_feat/2_enself_rt20v/genELexperiment2_07_04.json

  test_benchmark:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install feeed
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python main.py -o config_files/options/baseline.json -a config_files/algorithm/benchmark.json

    - name: Compare output
      run: diff output/benchmark/test_benchmark.csv output/benchmark/test_benchmark.csv

  test_augmentation:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install feeed
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python main.py -o config_files/options/baseline.json -a config_files/algorithm/augmentation.json

  test_evaluation-plotter:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get install build-essential python3 python3-dev

    - name: Install feeed
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python main.py -o config_files/options/baseline.json -a config_files/algorithm/evaluation_plotter.json

  test_integration:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get install build-essential python3 python3-dev

    - name: Install feeed
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python main.py -o config_files/options/baseline.json -a config_files/algorithm/experiment_test.json
