name: GEDI Test

# Specifies when the action should run
on:
  pull_request:
    branches:
      - main

# Specifies the jobs that are to be run
jobs:
  test:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install gedi
      run: |
        python -m pip install --upgrade pip
        conda env update --file .conda.yml
        conda init bash
        conda activate gedi

    # Running the test scripts and comparing the outputs
    - name: Run feature_extraction test
      run: python main.py -o config_files/options/baseline.json -a config_files/algorithm/feature_extraction.jso

    - name: Compare output
      run: diff output/benchmark/test_2_benchmark.csv output/benchmark/test_2_benchmark.csv
