name: GEDI Test

# Specifies when the action should run
on:
  pull_request:
    branches:
      - main
      - bpm24
      - demo-icpm24
  workflow_dispatch:

# Specifies the jobs that are to be run
jobs:
  test_feature_computation:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install local package
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Set PYTHONPATH for tests
      run: |
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run test
      run:
        pytest -v tests/test_feature_extraction.py --maxfail=1 --disable-warnings -q

  test_generation:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install local package
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Set PYTHONPATH for tests
      run: |
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run test
      run:
        pytest -v tests/test_generator.py --maxfail=1 --disable-warnings -q

  test_benchmark:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install locally
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python main.py -a config_files/pipeline_steps/benchmark.json

    - name: Convert output and validation to same encoding
      run: |
        iconv -f UTF-8 -t ASCII data/validation/test_benchmark.csv > data/validation/test_benchmark.csv
        iconv -f UTF-8 -t ASCII output/benchmark/test_benchmark.csv > output/benchmark/test_benchmark.csv

    - name: Compare output
      run: diff data/validation/test_benchmark.csv output/benchmark/test_benchmark.csv

  test_augmentation:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install locally
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python main.py -a config_files/pipeline_steps/augmentation.json

  test_evaluation-plotter:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get install build-essential python3 python3-dev

    - name: Install locally
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python main.py -a config_files/pipeline_steps/evaluation_plotter.json

  test_integration:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get install build-essential python3 python3-dev

    - name: Install locally
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python main.py -a config_files/test/experiment_test.json

  test_grid_experiments_script:
    runs-on: ubuntu-latest

    # Setting up a python envronment  for the test script to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get install build-essential python3 python3-dev

    - name: Install locally
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run test
      run:
        python gedi/utils/execute_grid_experiments.py config_files/test

    - name: Convert output and validation to same encoding
      run: iconv -f UTF-8 -t ASCII output/features/generated/2_bpic_features/2_ense_enseef_feat.csv > data/validation/2_ense_enseef_feat.csv

    - name: Compare output
      run: diff data/validation/2_ense_enseef_feat.csv output/features/generated/2_bpic_features/2_ense_enseef_feat.csv