name: GEDI Test

# Specifies when the action should run
on:
  pull_request:
    branches:
      - main
      - bpm24

# Specifies the jobs that are to be run
jobs:
  test_feature-extraction:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2

    - name: Create conda environment
      run: conda env create -f .conda.yml

    - name: Activate conda environment
      run: echo "conda activate gedi" >> $GITHUB_ENV
      shell: bash

    - name: Run test
      run: |
        conda activate gedi
        python main.py -o config_files/options/baseline.json -a config_files/algorithm/pipeline_steps/feature_extraction.json

    - name: Compare output
      run: diff data/validation/test_feat.csv data/test_feat.csv


  test_generation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2

    - name: Create conda environment
      run: conda env create -f .conda.yml

    - name: Activate conda environment
      run: echo "conda activate gedi" >> $GITHUB_ENV
      shell: bash

    - name: Run test
      run: |
        conda activate gedi
        python main.py -o config_files/options/baseline.json -a config_files/algorithm/pipeline_steps/generation.json

    - name: Compare output 1
      run: diff data/validation/genELexperiment2_07_04.json output/features/grid_feat/2_enself_rt20v/genELexperiment2_07_04.json

    - name: Compare output 2
      run: diff data/validation/genELexperiment1_04_02.json output/features/grid_feat/2_enself_rt20v/genELexperiment1_04_02.json

    - name: Compare output 3
      run: diff data/validation/genELexperiment3_04.json output/features/grid_feat/1_enself/genELexperiment3_04.json

    - name: Compare output 4
      run: diff data/validation/genELexperiment4_02.json output/features/grid_feat/1_rt20v/genELexperiment4_02.json


  test_benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2

    - name: Create conda environment
      run: conda env create -f .conda.yml

    - name: Activate conda environment
      run: echo "conda activate gedi" >> $GITHUB_ENV
      shell: bash

    - name: Run test
      run: |
        conda activate gedi
        python main.py -o config_files/options/baseline.json -a config_files/algorithm/pipeline_steps/benchmark.json

    - name: Convert output and validation to same encoding
      run: iconv -f UTF-8 -t ASCII output/benchmark/test_benchmark.csv > data/validation/test_benchmark.csv

    - name: Compare output
      run: diff data/validation/test_benchmark.csv output/benchmark/test_benchmark.csv


  test_augmentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2

    - name: Create conda environment
      run: conda env create -f .conda.yml

    - name: Activate conda environment
      run: echo "conda activate gedi" >> $GITHUB_ENV
      shell: bash

    - name: Run test
      run: |
        conda activate gedi
        python main.py -o config_files/options/baseline.json -a config_files/algorithm/pipeline_steps/augmentation.json


  test_evaluation-plotter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2

    - name: Create conda environment
      run: conda env create -f .conda.yml

    - name: Activate conda environment
      run: echo "conda activate gedi" >> $GITHUB_ENV
      shell: bash

    - name: Run test
      run: |
        conda activate gedi
        python main.py -o config_files/options/baseline.json -a config_files/algorithm/pipeline_steps/evaluation_plotter.json


  test_integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2

    - name: Create conda environment
      run: conda env create -f .conda.yml

    - name: Activate conda environment
      run: echo "conda activate gedi" >> $GITHUB_ENV
      shell: bash

    - name: Run test
      run: |
        conda activate gedi
        python main.py -o config_files/options/baseline.json -a config_files/algorithm/experiment_test.json


  test_grid_experiments_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2

    - name: Create conda environment
      run: conda env create -f .conda.yml

    - name: Activate conda environment
      run: echo "conda activate gedi" >> $GITHUB_ENV
      shell: bash

    - name: Run test
      run: |
        conda activate gedi
        python execute_grid_experiments.py config_files/algorithm/test

    - name: Convert output and validation to same encoding
      run: iconv -f UTF-8 -t ASCII output/features/generated/2_bpic_features/2_ense_enseef_feat.csv > data/validation/2_ense_enseef_feat.csv

    - name: Compare output
      run: diff data/validation/2_ense_enseef_feat.csv output/features/generated/2_bpic_features/2_ense_enseef_feat.csv
